{"uuid": "05ccc142-0bf7-4bcc-9684-4a4a05e8fcc0", "children": ["97513b21-390e-4330-881e-c0cadf9953aa"], "befores": [{"name": "small_jpg_image", "status": "passed", "start": 1753972609354, "stop": 1753972609485}], "afters": [{"name": "small_jpg_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'small_7847.jpg'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 67, in small_jpg_image\n    os.remove(img_path)\n"}, "start": 1753972610578, "stop": 1753972610587}], "start": 1753972609354, "stop": 1753972610587}