{"uuid": "f571bd22-f869-4eaf-9b04-ce573db1b495", "children": ["7e6cff13-af21-4b0d-87cd-3038660bdcfc"], "befores": [{"name": "small_jpg_image", "status": "passed", "start": 1753970524346, "stop": 1753970524493}], "afters": [{"name": "small_jpg_image::0", "status": "broken", "statusDetails": {"message": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'small_7960.jpg'\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Anaconda3\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\工作记录\\项目说明\\api_test\\tests\\conftest.py\", line 59, in small_jpg_image\n    os.remove(img_path)\n"}, "start": 1753970526719, "stop": 1753970526727}], "start": 1753970524346, "stop": 1753970526727}