{"name": "test_user_auth[case21]", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不符：预期400，实际403\nassert 403 == 400\n +  where 403 = <Response [403]>.status_code", "trace": "case = {'case_id': 'auth_022', 'expected_code': 400, 'expected_message': '当前密码不正确', 'expected_success': False, ...}\nauth_token = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjExNTUiLCJpYXQiOjE3NTM5NjgxMzcsImV4cCI6MTc1Mzk3NTMzN30.8Z0UL4YhRJFzi7N5EhkXevrBoOZeDF3M2eZnEcjJmSU'\nsmall_jpg_image = 'small_1512.jpg'\nlarge_jpg_image = 'large_4731.jpg'\nsmall_png_image = 'small_1587.png'\nlarge_png_image = 'large_3620.png'\nnon_image_file = 'test_6244.txt'\n\n    @allure.feature(\"用户认证模块\")\n    @pytest.mark.parametrize(\"case\", CASES)\n    def test_user_auth(case, auth_token, small_jpg_image, large_jpg_image, small_png_image, large_png_image, non_image_file):\n        allure.story(case[\"name\"])\n        allure.title(case[\"case_id\"] + \": \" + case[\"name\"])\n    \n        # 文件映射\n        file_map = {\n            \"test_avatar.jpg\": small_jpg_image,\n            \"large_avatar.jpg\": large_jpg_image,\n            \"test_avatar.png\": small_png_image,\n            \"large_avatar.png\": large_png_image,\n            \"test_file.txt\": non_image_file\n        }\n        # 预处理请求\n        request_data = preprocess_request(case, auth_token, file_map)\n    \n        # 发送请求\n        response = Request.send_request(\n            method=case[\"method\"],\n            endpoint=case[\"url\"],\n            json=request_data.get(\"json\"),\n            params=request_data.get(\"params\"),\n            headers=request_data.get(\"headers\"),\n            files=request_data.get(\"files\"),\n            token=auth_token\n        )\n    \n        # 断言\n>       assert_response(\n            response,\n            expected_code=case[\"expected_code\"],\n            expected_success=case.get(\"expected_success\"),\n            expected_message=case.get(\"expected_message\")\n        )\n\ntests\\test_user_auth.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [403]>, expected_code = 400\nexpected_success = False, expected_message = '当前密码不正确'\n\n    @allure.step(\"验证响应：状态码{expected_code}，消息{expected_message}\")\n    def assert_response(response, expected_code, expected_success=None, expected_message=None):\n        \"\"\"验证响应结果\"\"\"\n>       assert response.status_code == expected_code, \\\n            f\"状态码不符：预期{expected_code}，实际{response.status_code}\"\nE       AssertionError: 状态码不符：预期400，实际403\nE       assert 403 == 400\nE        +  where 403 = <Response [403]>.status_code\n\nutils\\test_utils.py:7: AssertionError"}, "steps": [{"name": "发送请求：'PUT' '/auth/userinfo'", "status": "passed", "attachments": [{"name": "请求信息", "source": "68ab64f0-d554-4288-9306-a5e279b2cc18-attachment.json", "type": "application/json"}, {"name": "响应信息", "source": "96ad5858-ad6e-42a0-a195-92ee21c14551-attachment.txt", "type": "text/plain"}, {"name": "响应体", "source": "ad0c30c9-2424-42b1-a267-782e593c920c-attachment.json", "type": "application/json"}], "parameters": [{"name": "method", "value": "'PUT'"}, {"name": "endpoint", "value": "'/auth/userinfo'"}, {"name": "headers", "value": "{'Authorization': 'Bearer '}"}, {"name": "params", "value": "{}"}, {"name": "json", "value": "{'oldPassword': 'Wrong123', 'newPassword': 'NewTest123', 'securityEmail': 'admin1155@example.com', 'verificationCode': '{verify_code}'}"}, {"name": "files", "value": "None"}, {"name": "token", "value": "'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbjExNTUiLCJpYXQiOjE3NTM5NjgxMzcsImV4cCI6MTc1Mzk3NTMzN30.8Z0UL4YhRJFzi7N5EhkXevrBoOZeDF3M2eZnEcjJmSU'"}], "start": 1753968178077, "stop": 1753968178089}, {"name": "验证响应：状态码400，消息'当前密码不正确'", "status": "failed", "statusDetails": {"message": "AssertionError: 状态码不符：预期400，实际403\nassert 403 == 400\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"D:\\Anaconda3\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"D:\\工作记录\\项目说明\\api_test\\utils\\test_utils.py\", line 7, in assert_response\n    assert response.status_code == expected_code, \\\n"}, "parameters": [{"name": "response", "value": "<Response [403]>"}, {"name": "expected_code", "value": "400"}, {"name": "expected_success", "value": "False"}, {"name": "expected_message", "value": "'当前密码不正确'"}], "start": 1753968178089, "stop": 1753968178090}], "parameters": [{"name": "case", "value": "{'case_id': 'auth_022', 'name': '旧密码错误', 'method': 'PUT', 'url': '/auth/userinfo', 'headers': {'Authorization': 'Bearer '}, 'json': {'oldPassword': 'Wrong123', 'newPassword': 'NewTest123', 'securityEmail': 'admin1155@example.com', 'verificationCode': '{verify_code}'}, 'expected_code': 400, 'expected_success': False, 'expected_message': '当前密码不正确'}"}], "start": 1753968178076, "stop": 1753968178091, "uuid": "d07a2633-c561-44a7-8ab9-fb56b44a91c4", "historyId": "202a3269a82cd80ae4d617241851e415", "testCaseId": "de18b51a986ebd96b4485f2c6341275e", "fullName": "tests.test_user_auth#test_user_auth", "labels": [{"name": "feature", "value": "用户认证模块"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_auth"}, {"name": "host", "value": "CYJ"}, {"name": "thread", "value": "22368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_auth"}], "titlePath": ["tests", "test_user_auth.py"]}